apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    app: game1
spec:
  replicas: 4
  selector:
    matchLabels:
      app: game1
  template:
    metadata:
      labels:
        app: game1
    spec:
        containers:
          - name: snakegame
            image: shoaibk7/myimg:latest
            ports:
              - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: svc1
    labels:
      app: game1
spec:
    type: NodePort
    selector:
      app: game1
    ports:
      - protocol: TCP
        port: 80
        targetPort: 80
        nodePort: 32132
      
